version: "2.0"
services:

 node-adeel:
  build:
   context: .
   dockerfile: Dockerfile
  volumes:
   - .:/app
  ports:
   - "80:5000"
  links:
   - my-mongo
  depends_on:
   - my-mongo
   


 my-mongo:
  image: mongo
  ports:
   - "27107:27107" 

