version: "2.0"
services:

 node-adeel:
  build:
   context: .
   dockerfile: Dockerfile
  volumes:
   - ./src:/usr/src/app/src
   - ./public/lib/bootstrap/dist/css/bootstrap.min.css:/usr/src/app/public/lib/bootstrap/dist/css/bootstrap.min.css
   - ./package.json:/usr/src/app/package.json
   - ./gulpfile.js:/usr/src/app/gulpfile.js
  ports:
   - "80:6000"
  links:
   - my-mongo
  depends_on:
   - my-mongo 


 my-mongo:
  image: mongo
  ports:
   - "27017:27017" 

