version: "2.0"
services:

 node-adeel:
  build:
   context: .
   dockerfile: Dockerfile
  volumes:
   - ./src:/usr/src/app/src
   - ./public/lib/bootstrap/dist/css/bootstrap.min.css:/usr/src/app/public/lib/bootstrap/dist/css/bootstrap.min.css
   - ./src/app.js:/usr/src/app/src/app.js
  ports:
   - "80:5000"
  links:
   - my-mongo
  depends_on:
   - my-mongo
   


 my-mongo:
  image: mongo
  ports:
   - "27107:27107" 

